version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    reviewers:
      - erunion
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    reviewers:
      - erunion
    labels:
      - dependencies
    commit-message:
      prefix: chore(deps)
      prefix-development: chore(deps-dev)
    ignore:
      - dependency-name: codemirror
        versions:
          - ">= 6"
      - dependency-name: codemirror-graphql
        versions:
          - ">= 2"
      - dependency-name: react
        versions:
          - ">= 18"
      - dependency-name: react-dom
        versions:
          - ">= 18"
