name: BundleWatch
on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Rebuild node-sass
        run: npm rebuild node-sass

      - name: Build bundles
        run: npm run build

      - name: Analyze Bundle
        run: npx bundlewatch
