name: BundleWatch
on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x

      - name: Install npm@7
        run: npm install -g npm@7

      - name: Install dependencies
        run: npm ci

      - name: Build bundles
        run: npm run build

      - name: node-sass hack
        run: npm rebuild node-sass

      - name: Analyze Bundle
        run: npx bundlewatch
